# tabbing and spacing
tabWidth: 4
semi: true
endOfLine: crlf
printWidth: 120

# code style
singleQuote: true
bracketSpacing: false
htmlWhitespaceSensitivity: css

# code formatting
jsxBracketSameLine: false
trailingComma: none
arrowParens: always
