# These are admin settings: https://www.netlifycms.org/docs/

site_url: https://tobydevlin.com
logo_url: https://tobydevlin.com/favicon.ico

backend:
 name: gitlab
 repo: MrAdjunctPanda/tobydevlin.com-2.0
 auth_type: implicit 
 app_id: 3065adbe9106cb96697ace01699f6cd7590b0a1f85c4b4fc542d7a48a1b7f632

media_folder: 'content/img/netlifyCMS' # Media files will be stored here

collections:
    - name: 'blog' # Used in URL route
      label: 'Blog Posts' # Used in the UI
      folder: 'content/blog' # The path to the folder where the documents are stored
      create: true # Allow users to create new documents in this collection
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template
      fields: # The fields for each document, usually in front matter
          - label: 'Layout'
            name: 'layout'
            widget: 'hidden'
            default: 'post'

          - label: 'Publish Date'
            name: 'date'
            widget: 'hidden'

          - label: 'Title'
            name: 'title'
            widget: 'string'

          - label: 'Publish'
            name: 'publish'
            widget: 'boolean'
            default: true

          - label: 'Featured Image'
            name: 'image'
            widget: 'image'

          - label: 'Tags'
            name: 'tags'
            widget: 'list'

          - label: 'Body'
            name: 'body'
            widget: 'markdown'
